name: Deploy to EC2 (DEV)

on:
  push:
    branches:
      - dev   # dev 브랜치에 push될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2   # 서울 리전

      - name: Deploy with CodeDeploy
        uses: aws-actions/aws-codedeploy-deploy@v1
        with:
          application-name: AuroraPassApp       # CodeDeploy 애플리케이션 이름
          deployment-group: aurorapass-ec2-dev  # 새로 만든 배포 그룹 이름
          bundle-type: zip
          revision-location: github
